# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BabyCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('brand', models.CharField(max_length=128)),
                ('origin', models.CharField(blank=True, max_length=128, null=True)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('pic_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('B', 'BabyCare'), ('F', 'Food'), ('H', 'Health'), ('U', 'Beauty'), ('S', 'Special')], default='B', max_length=2)),
                ('description', models.TextField(default=models.CharField(max_length=128, unique=True))),
                ('online_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('weight', models.CharField(max_length=128)),
                ('cup_price', models.IntegerField()),
                ('ingredient', models.TextField()),
                ('claim', models.TextField()),
                ('endorsement', models.TextField()),
                ('sub_category', models.CharField(choices=[('F', 'Other Baby Foods'), ('F4', 'Baby Food From 4 Mths'), ('F6', 'Baby Food From 6 Mths'), ('F9', 'Baby Food From 9 Mths'), ('F12', 'Baby Food From 12 Mths'), ('M', 'Medicinal Needs')], default='F', max_length=3)),
            ],
            options={
                'ordering': ['brand', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_pack', models.IntegerField()),
                ('serving_size', models.CharField(max_length=128)),
                ('enegry_per_serving', models.CharField(max_length=128)),
                ('enegry_per_100g', models.CharField(max_length=128)),
                ('protein_per_serving', models.CharField(max_length=128)),
                ('protein_per_100g', models.CharField(max_length=128)),
                ('fat_per_serving', models.CharField(max_length=128)),
                ('fat_per_100g', models.CharField(max_length=128)),
                ('carbohydrate_per_serving', models.CharField(max_length=128)),
                ('carbohydrate_per_100g', models.CharField(max_length=128)),
                ('sugars_per_serving', models.CharField(max_length=128)),
                ('sugars_per_100g', models.CharField(max_length=128)),
                ('sodium_per_serving', models.CharField(max_length=128)),
                ('sodium_per_100g', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='babycare',
            name='nutrition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deltago.Nutrition'),
        ),
    ]
