# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='fee',
            field=models.IntegerField(default=500),
        ),
    ]
