# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='volume_size',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
