# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0002_auto_20170727_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartship',
            old_name='is_choosed',
            new_name='is_chosen',
        ),
        migrations.AddField(
            model_name='cartship',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
