# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0002_auto_20170529_0622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='babycare',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='babycare',
            old_name='weight',
            new_name='volume_size',
        ),
        migrations.RemoveField(
            model_name='babycare',
            name='discount',
        ),
        migrations.AddField(
            model_name='babycare',
            name='special_price',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='babycare',
            name='was_price',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='babycare',
            name='brand',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='babycare',
            name='claim',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='babycare',
            name='cup_price',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='babycare',
            name='description',
            field=models.TextField(blank=True, default=models.CharField(max_length=128, unique=True), null=True),
        ),
        migrations.AlterField(
            model_name='babycare',
            name='endorsement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='babycare',
            name='ingredient',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='babycare',
            name='nutrition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deltago.Nutrition'),
        ),
        migrations.AlterField(
            model_name='babycare',
            name='price',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='babycare',
            name='sub_category',
            field=models.CharField(choices=[('F', 'Other Baby Foods'), ('F4', 'Baby Food From 4 Mths'), ('F6', 'Baby Food From 6 Mths'), ('F9', 'Baby Food From 9 Mths'), ('F12', 'Baby Food From 12 Mths'), ('M', 'Medicinal Needs'), ('T', 'toiletries'), ('N', 'nappies and liners')], default='F', max_length=3),
        ),
    ]
