# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0003_auto_20170608_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=128, null=True)),
                ('origin', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pic_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='babycare',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='babycare',
            name='cup_price',
        ),
        migrations.RemoveField(
            model_name='babycare',
            name='description',
        ),
        migrations.RemoveField(
            model_name='babycare',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='babycare',
            name='pic_url',
        ),
        migrations.AlterField(
            model_name='babycare',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='babycare',
            name='special_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='babycare',
            name='was_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='babycare',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deltago.Details'),
        ),
    ]
