# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0003_auto_20170728_0609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-unpaid_time']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='unpaind_time',
            new_name='unpaid_time',
        ),
    ]
