# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0004_auto_20170730_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='serial_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
