# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0006_auto_20170614_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babycare',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
