# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 23:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deltago', '0007_auto_20170806_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_useful', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='unuseful_number',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='useful_number',
        ),
        migrations.AddField(
            model_name='reviewship',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deltago.Comment'),
        ),
        migrations.AddField(
            model_name='reviewship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
