# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0009_babycaredetails_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babycare',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='babycaredetails',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
