# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0009_auto_20170821_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='special_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
