# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0010_auto_20170822_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='servings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
