# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0011_auto_20170827_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='pic_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
