# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0011_auto_20170703_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babycare',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
