# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0012_commodity_pic_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
