# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0013_auto_20170703_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('stockcode', models.CharField(max_length=128, unique=True)),
                ('model_name', models.CharField(max_length=128)),
            ],
        ),
    ]
