# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-31 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0013_auto_20170831_0436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ship',
            old_name='number',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='express',
            new_name='express_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency_unit',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ship_fee',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='ship',
            name='send_time',
        ),
        migrations.AddField(
            model_name='payment',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ship',
            name='express_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='state',
            field=models.CharField(choices=[('P', 'Processing'), ('D', 'Delivered')], default='P', max_length=4),
        ),
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='delivered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='linker',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='signer',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
