# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-01 01:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deltago', '0014_auto_20170831_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=128)),
                ('contact_number', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
