# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0016_order_payment_ship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='stockcode',
            new_name='commodity_id',
        ),
    ]
