# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0017_auto_20170717_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='stockcode',
        ),
        migrations.AddField(
            model_name='search',
            name='commodity_id',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='commodity_id',
            field=models.IntegerField(unique=True),
        ),
    ]
