# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0018_auto_20170718_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babycare',
            name='details',
        ),
        migrations.RemoveField(
            model_name='babycaredetails',
            name='stockcode',
        ),
        migrations.AddField(
            model_name='babycaredetails',
            name='commodity_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deltago.BabyCare'),
        ),
    ]
