# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0019_auto_20170718_0214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='babycare',
            options={},
        ),
    ]
