# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deltago', '0020_auto_20170718_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babycaredetails',
            old_name='commodity_id',
            new_name='babycare',
        ),
    ]
